on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Continuous integration

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: 1.56.0 # MSRV
            features: "\"\""
          - rust: 1.56.0 # MSRV
            features: "std"
          - rust: stable
            features: "\"\""
          - rust: stable
            features: "std"
          - rust: nightly
            features: "\"\""
          - rust: nightly
            features: "std"
          - rust: nightly
            features: "std, coerce"
          - rust: nightly
            features: "coerce"

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Tests
        run: |
          cargo test --verbose --no-default-features --features ${{ matrix.features }}

  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Test with Miri
        run: |
          cargo miri test
          cargo miri test --features nightly
